version: '3'
  
services:
  db:
    image: postgres
    restart: always
    environment:
      - PGPORT=7001
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres@2024dip
    ports:
      - "7001:5432"
  web:
    container_name: dip_back
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8001:8000"

networks:
  default:
    external:
      name: proxynetwork