# Generated by Django 5.1.3 on 2024-11-20 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='company',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='department',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='possible_date',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='title',
        ),
        migrations.AddField(
            model_name='interview',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Ярилцлага хийгдсэн эсэх'),
        ),
        migrations.AlterField(
            model_name='anket',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'Эрэгтэй'), (1, 'Эмэгтэй'), (2, 'Бусад')], null=True, verbose_name='Хүйс'),
        ),
        migrations.AlterField(
            model_name='award',
            name='anket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='main.anket'),
        ),
        migrations.AlterField(
            model_name='careercontact',
            name='anket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_contacts', to='main.anket'),
        ),
        migrations.AlterField(
            model_name='desicion',
            name='desicion_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Ажилд авах'), (1, 'Ажилд авахгүй'), (2, 'Санал болгох'), (3, 'Санал болгохгүй')], null=True, verbose_name='Шийдвэрийн төрөл'),
        ),
        migrations.AlterField(
            model_name='education',
            name='anket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='main.anket'),
        ),
        migrations.AlterField(
            model_name='family',
            name='anket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='main.anket'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='anket/c8b9a16af61e46d8813b9a6265ba21e8'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='anket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='main.anket'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='appearance',
            field=models.IntegerField(blank=True, choices=[(0, 'Хангалтгүй'), (1, 'Дунджаас доогуур'), (2, 'Дундаж'), (3, 'Сайн'), (4, 'Маш сайн')], null=True, verbose_name='Гадаад төрх'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='attitude',
            field=models.IntegerField(blank=True, choices=[(0, 'Хангалтгүй'), (1, 'Дунджаас доогуур'), (2, 'Дундаж'), (3, 'Сайн'), (4, 'Маш сайн')], null=True, verbose_name='Хандлага'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='communication',
            field=models.IntegerField(blank=True, choices=[(0, 'Хангалтгүй'), (1, 'Дунджаас доогуур'), (2, 'Дундаж'), (3, 'Сайн'), (4, 'Маш сайн')], null=True, verbose_name='Харилцаа өөрийгөө илэрхийлэх чадвар'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='independence',
            field=models.IntegerField(blank=True, choices=[(0, 'Хангалтгүй'), (1, 'Дунджаас доогуур'), (2, 'Дундаж'), (3, 'Сайн'), (4, 'Маш сайн')], null=True, verbose_name='Идэвх санаачлага'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='knowledge',
            field=models.IntegerField(blank=True, choices=[(0, 'Хангалтгүй'), (1, 'Дунджаас доогуур'), (2, 'Дундаж'), (3, 'Сайн'), (4, 'Маш сайн')], null=True, verbose_name='Мэдлэг, авъяас'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='leadership',
            field=models.IntegerField(blank=True, choices=[(0, 'Хангалтгүй'), (1, 'Дунджаас доогуур'), (2, 'Дундаж'), (3, 'Сайн'), (4, 'Маш сайн')], null=True, verbose_name='Манлайлал болон багаар ажиллах'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='logic_skill',
            field=models.IntegerField(blank=True, choices=[(0, 'Хангалтгүй'), (1, 'Дунджаас доогуур'), (2, 'Дундаж'), (3, 'Сайн'), (4, 'Маш сайн')], null=True, verbose_name='Асуултад хариулж буй байдал'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='overall_score',
            field=models.IntegerField(blank=True, choices=[(0, 'Хангалтгүй'), (1, 'Дунджаас доогуур'), (2, 'Дундаж'), (3, 'Сайн'), (4, 'Маш сайн')], null=True, verbose_name='Нэгдсэн дүгнэлт'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='responsibility',
            field=models.IntegerField(blank=True, choices=[(0, 'Хангалтгүй'), (1, 'Дунджаас доогуур'), (2, 'Дундаж'), (3, 'Сайн'), (4, 'Маш сайн')], null=True, verbose_name='Өөрийгөө хөгжүүлэх зан чанар'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Санал болгосон'), (1, 'Санал болгоогүй'), (2, 'Ажилд авсан'), (3, 'Ажилд аваагүй')], null=True, verbose_name='Ярилцлагийн статус'),
        ),
        migrations.AlterField(
            model_name='language',
            name='anket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='main.anket'),
        ),
        migrations.AlterField(
            model_name='priorcareer',
            name='anket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prior_careers', to='main.anket'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Хүний нөөцийн ажилтан'), (1, 'Захирал'), (2, 'Администратор'), (3, 'Ажилтан')], default=0, verbose_name='Хэрэглэгчийн төрөл'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='anket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.anket'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='anket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='main.anket'),
        ),
    ]
