# Generated by Django 5.1.3 on 2024-11-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_interview_company_remove_interview_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='is_scheduled',
            field=models.BooleanField(default=False, verbose_name='Цаг товлосон эсэх'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='anket/f4085e984e6c4b18b6e8f299867e9320'),
        ),
    ]
