# Generated by Django 5.1.3 on 2024-11-20 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_interview_is_final_alter_image_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anket',
            name='level_count',
        ),
        migrations.AddField(
            model_name='schedule',
            name='interview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.interview'),
        ),
        migrations.AlterField(
            model_name='anket',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Ажил горилогч'), (1, 'Ажилтан'), (2, 'Түтгэлзсэн')], null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='anket/1191cde1b91f4a9bb793091e272e943e'),
        ),
    ]
