# Generated by Django 5.1.3 on 2024-11-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_anket_level_count_schedule_interview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='anket/4049e2e4de7d460cb38f9ccceaae593a'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='level',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Хэд дэх ярилцлага'),
        ),
        migrations.DeleteModel(
            name='Desicion',
        ),
    ]
