# Generated by Django 5.1.3 on 2024-12-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_image_photo_alter_interview_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anket',
            name='blood',
            field=models.IntegerField(blank=True, choices=[(1, 'O'), (2, 'A'), (3, 'B'), (4, 'AB')], null=True, verbose_name='Цусны бүлэг'),
        ),
        migrations.AlterField(
            model_name='anket',
            name='driver_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Үнэмлэхгүй'), (1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'M'), (7, 'B C D'), (8, 'B C M E'), (9, 'B C'), (10, 'B M'), (11, 'B C M'), (12, 'B C D M'), (13, 'B C D E')], null=True, verbose_name='Жолооны ангилал'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='anket/29a36c0dba344266b363b4c43369dea4'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='conclution_points',
            field=models.CharField(blank=True, null=True, verbose_name='Нэгдсэн дүгнэлт (оноо)'),
        ),
    ]
